### PR TITLE
Notify about the macOS Big Sur Beta 10+ issue

### PR DESCRIPTION
**Pull request by superkid200**
Notify about the macOS Big Sur Beta 10+ issue as Apple Secure Boot is broken.

### CODE REVIEW

**Comment by khronokernel** [comment]
https://github.com/dortania/OpenCore-Post-Install/commit/b134fba08dac7cf38006d80d96346b4069c26ce8

**Comment by superkid200** [comment]
Idk why I didn’t receive the site update because yesterday it didn’t show Note 2?

**Comment by 1alessandro1** [comment]
Secure boot support was fixed with OpenCore 0.6.3

https://github.com/acidanthera/OpenCorePkg/commit/aea1c578c2c044ebddb96688ccef27a6a915466f#diff-82666491e8d181f6fa834420291df3b84252a717332a316f0932f0b18e69dbbdR278

**Comment by superkid200** [comment]
It’s an outdated PR now.

**Pull request closed without merging**
