### PR TITLE
Updated and heavily tested iServices tutorial.

### PR DESCRIPTION
**Pull request by sickcodes**
- Added https://github.com/sickcodes/osx-serial-generator instructions

It's a wrapper for your `macserial` as well as a trivial uuidgen plus a proper MAC Address from https://gitlab.com/wireshark/wireshark/-/raw/master/manuf

Most of the existing information on the page is redundant, contrary to hearsay.

iServices has been heavily tested by myself and others at https://github.com/sickcodes/Docker-OSX

Works every time now!

Really appreciate the documentation that is there currently, hence added both options.

Thank you, a ton!

### CODE REVIEW

**Comment by vit9696** [comment]
I am afraid we shall not accept link to the tools that look like malware (since when installing a VM is needed to generate the values?) or refer to apparently inadequate guides written with legs, sorry. If you have constructive issues with the guide as it is, which in fact is written based on the [Russian](https://applelife.ru/posts/727913) guide designed by AppleLife staff with my direct participation, please do clearly outline them first before making groundless claims nobody here would take for granted.

Besides that, I am sorry, but your kludge does not seem to add anything decent to the community needs apart from constant self-promotion and donation requests. It is not how things work here.

**Comment by khronokernel** [comment]
This is disappointing, no mention of macserial at all:
* https://github.com/sickcodes/osx-serial-generator

Should at least have the decency to add on the README to mention who's code is doing the heavy lifting...

**Comment by sickcodes** [comment]
Hey @vit9696, thanks for the quick response.

Thank you for pointing out the OSX-KVM redundant download. You are correct, that is not required if only generating serial numbers, I just removed that: https://github.com/sickcodes/osx-serial-generator/pull/8/

Ok so the issues that I have identified are the following:

1. Apple support does not affect iMessages login procedure in any way. "Invalid", Valid, Used are all equal.
2. `macserial` must be used to generate SERIAL + BOARD_SERIAL.
2. smUUID can be completely random.
3. Builtin vs. builtin: This information regarding network interfaces is not required. You simply need to use a MAC Address that is `Apple, Inc.`.
4. You do not need to remove any cache files between attempts.

I create machines with X everywhere and can log into iMessage every single time on reboot by changing 

```xml
    <key>MLB</key>
    <string>{{BOARD_SERIAL}}</string>
    <key>ROM</key>
    <data>{{ROM}}</data>
    <key>SpoofVendor</key>
    <true/>
    <key>SystemProductName</key>
    <string>{{DEVICE_MODEL}}</string>
    <key>SystemSerialNumber</key>
    <string>{{SERIAL}}</string>
    <key>SystemUUID</key>
    <string>{{UUID}}</string>
```

In fact, I use:

DEVICE_MODEL=iMacPro1,1
SERIAL=XXXXXXXXXXXX
BOARD_SERIAL=XXXXXXXXXXXXXXXXX
UUID=XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
MAC_ADDRESS=00:03:93:00:00:00

and generate a fresh set, without deleting cache and can log in every single time from datacenter IP, from real IP, from VPN IP.

This is correct: https://github.com/dortania/OpenCore-Post-Install/blob/master/universal/iservices.md#cleaning-up-your-appleid

**Comment by sickcodes** [comment]
@khronokernel thank you for reminding me. I have a link to the project, but do not directly outline the tool, added here: https://github.com/sickcodes/osx-serial-generator#upstream-thanks

Previously we used Clover, and I have not updated the upstream credits on either repo.

The serial generator was a folder inside Docker-OSX and I moved it to it's own repo.

I always thank upstream and contributions and I appreciate your work...

Regarding donations, @vit9696 nobody has ever paid a donation, the project is GPLv3+, the Sponsor links were removed a few weeks ago. Nobody ever paid a cent.

**Comment by khronokernel** [comment]
> Builtin vs. builtin: This information regarding network interfaces is not required. You simply need to use a MAC Address that is Apple, Inc..

`Built-in` is important to ensure the App Store works properly - we include it as part of the iServices tutorial as it wouldn't be worth making a separate page. Generally the driver should add the property automatically however sometimes it's required to be defined by the end-user. Additionally, using a standard MAC address is fine without `Apple, Inc` and simply setting `Built-in`

**Comment by sickcodes** [comment]
I agree with you both.. we are on the same team 😅 I fully appreciate the OpenCore project but like I said before we were using the Clover bootloader and I apologize for not updating Docker-OSX to state that we are using OpenCore yet.

For us, we found that built-in did not matter and neither did en0 or en1 differences, nor did using e1000 or vmxnet3 KVM interfaces.

That discussion was here: https://forums.unraid.net/topic/100416-big-sir-macinabox-icloud-works-but-imessage-error/

**Comment by sickcodes** [comment]
FWIW @khronokernel at least we are using macserial latest, it is also verbose and clearly outlines that it's compiling macserial from OpenCore and it's also the first thing that happens.


Regarding GenSMBIOS, I originally was going to use that, as outlined in this comment https://www.reddit.com/r/hackintosh/comments/m0gwnh/osx_serial_generator_automatically_generate/gq7sck1/?utm_source=share&utm_medium=ios_app&utm_name=iossmf&context=3

However ended up wrapping macserial because your project already provides shell options for the macserial binary which was fantastic.

The only reason I wrote the shell script was because we needed iMessage automatically instead of users wasting thousands of hours setting it up, explained here:

"I looked at GenSMBIOS before writing this for Docker-OSX, but it didn’t have enough shell options, namely Mac Addresses, UUID, and ROMs.

"Also couldn’t script GenSMBIOS because the menu was difficult to use. This is for mass generating serials, or specific boot disks from a given serial set.

"I added the ability to automatically create OpenCore.qcow as well as custom plists, sourceable env files, TSV and CSV output :)

"This also compiles macserial latest at runtime as opposed to using an unmaintaned repo version."

Hence why I am writing this PR because this solution works every time for us, and I thought you would appreciate rather than keeping it in a lonely folder on docker-OSX.

The project has ~70,000 installs, which grew 20k since I added the macserial wrapper. Only one user has reported the Apple Support error so far and he was also unable to login on a real Mac.

**Comment by mhaeuser** [comment]
> The project has ~70,000 installs, which grew 20k since I added the macserial wrapper. Only one user has reported the Apple Support error so far and he was also unable to login on a real Mac.

In a very short amount of time (compared to the previous research), with a limited set of macOS versions, and with limited feedback and testing. Automated installs of realistically a few serious users are not representative for a huge variety of user setups and real-world Apple accounts over the course of many years. There is no indication your proposals to change anything about the currently recommended practices are adequate or required.

> I looked at GenSMBIOS before writing this for Docker-OSX, but it didn’t have enough shell options, namely Mac Addresses, UUID, and ROMs.

Then if you were to reasonably contribute, you would be in contact with the developers of existing, wide-spread solutions. We are not interested in pointless fragmentation. I do not care much about (carelessly missed) accreditation personally, but I do care about general ethics. We accept third-party solutions into our recommendations for exactly this, when we recommend it, not for when they are proposed out of self-promotion.

Good luck with your project.

**Comment by khronokernel** [comment]
> For us, we found that built-in did not matter and neither did en0 or en1 differences, nor did using e1000 or vmxnet3 KVM interfaces.

> That discussion was here: forums.unraid.net/topic/100416-big-sir-macinabox-icloud-works-but-imessage-error

From that same link:

> Unfortunately that didn't work. I went this route instead, and that worked flawlessly for me: https://dortania.github.io/OpenCore-Post-Install/universal/iservices.html#fixing-en0
> The issue can be fixed easily, for example changing vmxnet3 to e1000-82545em, or by adding the built in property to en0, or fixing wrong smbios data, or it can be more difficult:
> This solution worked for me! I ended up not needing the NullEthernet patch but I followed the steps for properly adding the en0 to the config file and afterwards iCloud/iMessage/Facetime worked with no issues.

> This also compiles macserial latest at runtime as opposed to using an unmaintaned repo version.

Which also limits it to macOS (and with Command Line Tools installed) and Linux (with the appropriate packages), which is a significantly smaller subset of our audience. If you're going to make the claim that users waste "thousands of hours setting it up":
1. This does not apply to our audience
2. Something that is native and has an actual UI is much easier to use than something that requires the CLT to be downloaded and then args passed on the command line
And how exactly is it an "unmaintained repo version"? In fact, building from `master` is not advised as the `master` branch is not guaranteed to work at all. The releases should be used for end users.


> The project has ~70,000 installs, which grew 20k since I added the macserial wrapper. Only one user has reported the Apple Support error so far and he was also unable to login on a real Mac.

This is a virtual machine, I don't think you realize just how different actual hardware is...
If you're using the same exact environment endlessly as your argument that it has been tested and proven, I'm sorry but that's not realistic at all.

We're not supporting this, especially after [claims like this](https://www.vice.com/en/article/akdmb8/open-source-app-lets-anyone-create-a-virtual-army-of-hackintoshes) and [the author clearly supporting the misleading information inside...](https://twitter.com/sickcodes/status/1370051001697198081?s=21):

> Previously, this process was something of guesswork. Hackintosh users have long had this problem, but have basically had to use guesswork to figure out valid serial codes so they could use iMessage.

Not like this was [well documented](https://github.com/acidanthera/OpenCorePkg/blob/master/Utilities/macserial/FORMAT.md)...

Dortania nor Acidanthera are going to supporting a program like this, especially if the author makes baseless claims for real hardware. You really have the Linux mentality of "I've tested endlessly on my machine, so clearly it's perfect" especially as VMs are endlessly replicable compared to the hundreds of thousands of different hardware, firmware and software variations on real world PCs.

**Comment by sickcodes** [comment]
@mhaeuser I think everyone misunderstands why I even contributed today. I didn't write any of the code for OpenCore.

I write it to for our own needs, period. The serial generator script was written for our project's own use, it was a shell wrapper for macserial, which already has its own options.

Sorry for not asking permission to write code for ourselves?

I wanted to use GenSMBIOS, but it's unscriptable for unattended use. Then I saw it's a wrapper for macserial. It's written in Python, and we don't need python in the container. The serial generator is a just a tiny script for our Docker version of your great product, to generate full OpenCore EFI bootable disks using @kholia's work, at runtime, with unique serial numbers each and every single time - completely different realm of purpose.

It works every single time, flawlessly, so I [moved it to its own repo](https://github.com/sickcodes/Docker-OSX/commit/ab9761adb743713646c537f464514b3e0eba46de) so **other people could enjoy it too**.

I have no idea what self-promotion discussions you've had about me, there are no donations, none. Zilch. Nada. People use Docker-OSX, all day every day, **for free**. Some people don't have time they pay me to craft solutions. It's GPLv3+.

If you actually read the code on the project, you may have a better idea about why I made it, instead of abusing me as some self-promoter. The word OpenCore appears a thousands times when you run Docker-OSX.

No idea why you're all so hostile towards a PR. Donations were removed over a week ago (nobody pays for free software) but at least I know what you guys have been thinking about our project over the last few months. Weren't even using OpenCore in the beginning. Sorry for thinking this might be of use to your project. Great to meet you all.

**Comment by mhaeuser** [comment]
> Sorry for not asking permission to write code for ourselves?

Write code all you want, that is what licenses are for. You are asking to have references to your project upstreamed into community recommendations, and that is what you get comments for. You are saying it yourself, the software is designed to suit **your** needs, not for what makes sense for the community ecosystem. Submitting "use my project" is not a contribution by any reasonable metric. If you want to contribute, advance existing solutions for more use-cases. Otherwise call your submissions what they are, or we will do it for you.

**Comment by sickcodes** [comment]
What do you mean call it out for what it is? What do you think it is?

I know what it is:

A 200 line macserial wrapper + uuidgen + download MAC address list and randomize the last 3 octects.

Do you know what GenSMBIOS does? Do you know what mine does?

It's just a script to use macserial, which has to be compiled, hence the script. It literally compiles macserial.

**Comment by khronokernel** [comment]
@sickcodes You're missing the point again...

It's the combination of software and the info you provide that's the issue. Your repo and the changes made are misleading users, and so we have no interest in supporting this PR. If you're still going to stand your ground on your beliefs, not be able to back them up and not accept any of this discussion, then what do you want from this PR? You clearly have no interest in adapting and we have no interest in merging as-is

**Comment by mhaeuser** [comment]
> What do you think it is?

As I already said, self-promotion.

> A 200 line macserial wrapper + uuidgen + download MAC address list and randomize the last 3 octects.

The smaller and more insignificant it is, the less place is there for it to exist outside of mainline.

> Do you know what GenSMBIOS does? Do you know what mine does?

Roughly, I did not check your script in detail. After being linked that ridiculous Vice article, I took a small peak. You present yours as an alternative yourself by your PR, outlining them as "Option 1" and "Option 2" (pushing the commonly-accepted standard to number 2 no less). Whether the missing functionality your script provides would be an extension to GenSMBIOS (in case of a more involved community-beneficial functionality), or to macserial (helper script) does not matter for the point of the debate.

Look, we are a community organisation aiming to provide useful services to the community. By thinking to make a point with "I didn't write any of the code for OpenCore. I write it to for our own needs, period.", you make mine. **Your** needs are not of any interest here so long as you do not aim to improve existing infrastructure in a constructive way. Just because you do not take donations, it doesn't make it a valuable contribution. Write code here for the community, or take it elsewhere.

**Comment by sickcodes** [comment]
If you have a problem with a sensationalized story Vice wrote about a downstream version of your project, you might want to take that up with the author of the article, I didn't write it.

**Comment by mhaeuser** [comment]
Did you CTRL+F for "Vice" or read the message? This discussion is over.

**Pull request closed without merging**
