### PR TITLE
Post-install steps for Windows and VMWare users

### PR DESCRIPTION
**Pull request by cowwoc**
Credits:
* https://www.youtube.com/watch?v=jvb-BIMV1Mw&feature=youtu.be&t=2740
* https://www.reddit.com/r/hackintosh/comments/j0o5fq/opencore_on_amd_vmware_workstation/

### CODE REVIEW

**Comment by 1Revenger1** [comment]
I'm...confused

* Normally, post installation is done in macOS, so windows instructions don't make a lot of sense.
* Clover Configurator doesn't even run in Windows
* Any reason to add Bootstrap.efi manually? BootProtect being enabled does that automatically anyways.

**Comment by cowwoc** [comment]
Hi @1Revenger1

* I didn't realize that I was supposed to run these steps inside the new OS installation. Let me try running `MountEFI` inside the installation tomorrow and we can probably remove the Windows section.
* I'm not familiar with `BootProtect`. When I run under VMWare Workstation 16 I see the following boot options:

1. `OpenCore` which maps to `PciRoot(0x0)/Pci(0x16,0x0)/Pci(0x0,0x0)/USB(0x0,0x0)/HD(1,MBR,0x41817E01,0x800,0x64000)/EFI\OC\Bootstrap\Bootstrap.efi)`. The path is correct but we don't want to boot off the USB.
2. `EFI VMware Virtual SATA Hard Drive (0.0)` which maps to `PciRoot(0x0)/Pci(0x11,0x0)/Pci(0x4,0x0)/Sata(0x0,0x0,0x0)`. If I boot this, I get `The CPU has been disabled by the guest operating system. Power off or reset the virtual machine.` on verbose output line `[EB|#LOG:EXITBS:START]`.
3. The new boot option I add (which works) gets mapped to `PciRoot(0x0)/Pci(0x11,0x0)/Pci(0x4,0x0)/Sata(0x0,0x0,0x0)/HD(1,GPT,DF3BC978-AD8E-4CD8-AC3B-E4034-180C25E,0X28,0X64000)/\EFI\OC\Bootstrap\Bootstrap.efi`

The only difference between option 2 and 3 is the explicit EFI path yet it makes the difference. To be clear, my EFI partition just contains an `EFI` folder with all the files off the USB. There are no other files in the root directory of the partition. Did I miss something?

**Comment by cowwoc** [comment]
@1Revenger1 So I went back and ran `MountEFI` from within the new macOS installation. That worked but it still did not have the desired effect.

* The mounted EFI on the install drive is empty. It does not contain Apple/EFI as seen in the screenshot. Is this normal?
* I copied the EFI folder over from the bootable USB and rebooted. This did not help. I still got the same VMWare error on `[EB|#LOG:EXITBS:START]`.

Either I am doing something wrong, or VMware Workstation 16 does not work as you mentioned. Are you able to reproduce this problem on your end?

**Comment by dhinakg** [comment]
> The mounted EFI on the install drive is completely empty. It does not contain EFI/Apple as seen in the screenshot. Is this normal?

Yes, this won't exist until macOS decides to do a firmware update.

> I copied the EFI folder over from the bootable USB and rebooted. This did not help. I still got the same VMWare error on `[EB|#LOG:EXITBS:START]`.

I believe this is due to VMware emulating the Apple boot model. Running `bless` on `Bootstrap.efi` from macOS before rebooting should work.

**Comment by cowwoc** [comment]
@dhinakg so if I understand you correctly, I need to:

* Use `MountEFI` to mount the EFI partition
* Copy `EFI` from the Bootable USB to the EFI partition
* Run `sudo bless --folder /Volumes/EFI --file /Volumes/EFI/EFI/OC/Bootstrap/Bootstrap.efi --setBoot`
* Reboot

I tried that and the boot menu was not modified. Am I doing anything wrong?

**Comment by henriquejourdan** [comment]
I'm need to attach usb interfaces to Vmware fusion but the icon is gray (no usb detected). 
Tested on IMac 2009 osx Catalina and Sequoia. Both detects USB interfaces.
Fusion 12 and 13 don't.
High Sierra + Fusion: detect and connects USB.
What I'm doing wrong?

**Pull request closed without merging**
